version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myproject
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/libs/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: myproject
      DB_USER: myproject
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432

volumes:
  db_data: